name: todo_app_pro_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #DataBase
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #Generate UID
  uuid: ^3.0.5

  #Provides internalization and localization facilities
  intl: ^0.17.0

  #Animation
  animate_do: ^2.1.0

  #Dialogs
  panara_dialogs: ^0.1.2

  #Animations exported as json
  lottie: ^1.4.0

  #Toast
  ftoast: ^2.0.0

  #Slider
  flutter_slider_drawer: ^2.1.1

  #Data Picker
  flutter_cupertino_date_picker_fork: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/lottie/
